import { useState } from 'react'
import { getContent, saveContent } from '../data/content.js'
import './dashboard-modern.css'

const groups = [['Content Management', ['Home Section', 'Our Story', 'Catalog', 'Visit Us', 'Contact', 'Community']], ['Other', ['Settings']]]
const stats = [['4', 'Sections', 'Total editable sections', 'story'], ['12', 'Catalog Items', 'Products in your catalog', 'catalog'], ['5', 'Media Files', 'Images and assets', 'media'], ['3', 'Enquiries', 'Unread contact messages', 'contact']]
const actions = [['Home Section', 'Edit hero, intro and homepage photos', 'home'], ['Our Story', 'Edit story copy and image', 'story'], ['Catalog', 'Edit products, categories and photos', 'catalog'], ['Visit Us', 'Edit address, hours and phone', 'contact'], ['Contact', 'Edit enquiry copy and contact number', 'contact'], ['Community', 'Edit your community group link', 'contact']]
const updates = [['Home section updated', 'Hero content was refreshed', '2 hours ago'], ['Catalog item added', 'Dainty Ring Collection', '1 day ago'], ['Contact details updated', 'Store location and hours', '3 days ago']]
const iconFor = (label) => label.includes('Home') ? 'home' : label.includes('Story') || label === 'Sections' ? 'story' : label.includes('Catalog') ? 'catalog' : label.includes('Contact') || label.includes('Visit') || label.includes('Community') || label === 'Enquiries' ? 'contact' : label.includes('Media') ? 'media' : label === 'Settings' ? 'settings' : 'dashboard'
function Icon({ type }) { const symbols = { arrow: '→', bell: '♧', logout: '↪', home: '⌂', catalog: '◇', media: '▧', contact: '✉', story: '▤', settings: '⚙', dashboard: '▦' }; return <span className="dash-symbol" aria-hidden="true">{symbols[type] || symbols.dashboard}</span> }
function Field({ label, value, onChange, area = false }) { const props = { value: value || '', onChange: (event) => onChange(event.target.value), placeholder: label }; return <label className="editor-field"><span>{label}</span>{area ? <textarea {...props} rows="3" /> : <input {...props} />}</label> }
function ImageField({ label, value, onChange }) { const upload = (event) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => onChange(reader.result); reader.readAsDataURL(file) }; return <label className="editor-field image-field"><span>{label}</span><div className="image-upload-row"><input value={value || ''} onChange={(event) => onChange(event.target.value)} placeholder="Paste image URL or upload a file" /><label className="upload-button">Upload image<input type="file" accept="image/*" onChange={upload} /></label></div>{value && <img className="image-upload-preview" src={value} alt="Selected preview" />}</label> }
function CatalogEditor({ draft, setDraft }) {
  const [selected, setSelected] = useState(0)
  const product = draft.products[selected]
  const updateProduct = (field, value) => { const products = [...draft.products]; products[selected] = { ...product, [field]: value }; setDraft({ ...draft, products }) }
  const addProduct = () => { const next = { id: `product-${Date.now()}`, name: 'New product', description: '', image: '', category: 'all', label: 'New' }; setDraft({ ...draft, products: [...draft.products, next] }); setSelected(draft.products.length) }
  const removeProduct = () => { if (draft.products.length < 2) return; const products = draft.products.filter((_, index) => index !== selected); setDraft({ ...draft, products }); setSelected(Math.max(0, selected - 1)) }
  const addCategory = () => setDraft({ ...draft, catalog: { ...draft.catalog, categories: [...draft.catalog.categories, { id: `category-${Date.now()}`, label: 'New category' }] } })
  const updateCategory = (index, field, value) => setDraft({ ...draft, catalog: { ...draft.catalog, categories: draft.catalog.categories.map((category, categoryIndex) => categoryIndex === index ? { ...category, [field]: value } : category) } })
  const removeCategory = (index) => { if (draft.catalog.categories.length < 2) return; setDraft({ ...draft, catalog: { ...draft.catalog, categories: draft.catalog.categories.filter((_, categoryIndex) => categoryIndex !== index) } }) }
  if (!product) return <div className="empty-editor">Add your first product to begin.</div>
  return <><div className="catalog-manage-block"><div className="catalog-block-heading"><div><h3>Categories</h3><p>These become the filter buttons on your catalog.</p></div><button className="small-action" onClick={addCategory}>+ Add category</button></div>{draft.catalog.categories.map((category, index) => <div className="category-row" key={category.id}><input value={category.label} onChange={(event) => updateCategory(index, 'label', event.target.value)} aria-label={`Category ${index + 1} label`} /><input value={category.id} onChange={(event) => updateCategory(index, 'id', event.target.value)} aria-label={`Category ${index + 1} id`} /><button onClick={() => removeCategory(index)} disabled={draft.catalog.categories.length < 2}>Remove</button></div>)}</div><div className="catalog-product-picker"><div className="catalog-block-heading"><div><p>Products</p><h3>Choose a product to edit</h3></div><button className="small-action" onClick={addProduct}>+ Add product</button></div>{draft.products.map((item, index) => <button className={selected === index ? 'selected' : ''} key={item.id} onClick={() => setSelected(index)}><span>{String(index + 1).padStart(2, '0')}</span>{item.name}</button>)}</div><div className="catalog-product-form"><div className="selected-product-heading"><div><p>PRODUCT {String(selected + 1).padStart(2, '0')} OF {draft.products.length}</p><h3>{product.name}</h3></div><button className="remove-product" onClick={removeProduct} disabled={draft.products.length < 2}>Remove product</button></div><div className="editor-fields"><Field label="Product name" value={product.name} onChange={(value) => updateProduct('name', value)} /><ImageField label="Product photo" value={product.image} onChange={(value) => updateProduct('image', value)} /><Field label="Category id" value={product.category} onChange={(value) => updateProduct('category', value)} /><Field label="Small label" value={product.label} onChange={(value) => updateProduct('label', value)} /><Field label="Description" value={product.description} area onChange={(value) => updateProduct('description', value)} /></div></div></>
}
function Editor({ section, initial, onSaved, onBack }) {
  const [draft, setDraft] = useState(JSON.parse(JSON.stringify(initial)))
  const [saved, setSaved] = useState(false)
  const setValue = (group, field, value) => setDraft({ ...draft, [group]: { ...draft[group], [field]: value } })
  const save = () => { saveContent(draft); onSaved(draft); setSaved(true) }
  const field = (group, name, label, area = false) => <Field key={`${group}-${name}`} label={label} value={name === 'paragraphs' ? draft[group][name].join('\n') : draft[group][name]} area={area} onChange={(value) => setValue(group, name, name === 'paragraphs' ? value.split('\n') : value)} />
  let body
  if (section === 'Catalog') body = <CatalogEditor draft={draft} setDraft={setDraft} />
  if (section === 'Home Section') body = <div className="editor-fields">{field('home', 'eyebrow', 'Hero eyebrow')}{field('home', 'titleLine1', 'Title line 1')}{field('home', 'titleLine2', 'Title line 2')}{field('home', 'titleLine3', 'Title line 3')}{field('home', 'description', 'Hero description', true)}{field('home', 'location', 'Location')}{field('home', 'introEyebrow', 'Intro eyebrow')}{field('home', 'introTitle', 'Intro title')}{field('home', 'introText', 'Intro text', true)}{draft.home.heroImages.map((image, index) => <ImageField key={image + index} label={`Hero photo ${index + 1}`} value={image} onChange={(value) => setDraft({ ...draft, home: { ...draft.home, heroImages: draft.home.heroImages.map((item, itemIndex) => itemIndex === index ? value : item) } })} />)}</div>
  if (section === 'Our Story') body = <div className="editor-fields">{field('story', 'eyebrow', 'Eyebrow')}{field('story', 'tag', 'Image tag')}{field('story', 'title', 'Title')}{field('story', 'paragraphs', 'Paragraphs (one per line)', true)}<ImageField label="Story photo" value={draft.story.image} onChange={(value) => setValue('story', 'image', value)} /></div>
  if (section === 'Visit Us') body = <div className="editor-fields">{field('visit', 'heading', 'Heading')}<ImageField label="Visit photo" value={draft.visit.image} onChange={(value) => setValue('visit', 'image', value)} />{field('settings', 'address', 'Address', true)}{field('settings', 'hours', 'Opening hours')}{field('settings', 'phone', 'Phone')}{field('settings', 'mapsAddress', 'Maps address', true)}</div>
  if (section === 'Contact') body = <div className="editor-fields">{field('contact', 'heading', 'Heading')}{field('contact', 'intro', 'Intro text', true)}{field('contact', 'inquiryHeading', 'Inquiry heading')}{field('contact', 'inquiryText', 'Inquiry text', true)}</div>
  if (section === 'Community') body = <div className="editor-fields">{field('community', 'heading', 'Heading')}{field('community', 'text', 'Description', true)}{field('community', 'link', 'Community group link')}</div>
  if (section === 'Settings') body = <div className="editor-fields">{field('settings', 'phone', 'Phone')}{field('settings', 'address', 'Address', true)}{field('settings', 'hours', 'Opening hours')}{field('settings', 'mapsAddress', 'Maps address', true)}{field('community', 'link', 'Community group link')}</div>
  return <div className="editor-workspace"><div className="editor-workspace-head"><button className="back-button" onClick={onBack}>← Overview</button><div><p className="editor-kicker">CONTENT EDITOR</p><h2>{section}</h2><p>Make your changes below, then select Save when you are ready.</p></div><button className="save-button" onClick={save}>Save Changes</button></div>{saved && <p className="save-confirmation">Changes saved. Reload the public site to see the updated content.</p>}{body}</div>
}
function NavLink({ label, active, setActive }) { return <button className={`side-link ${active === label ? 'active' : ''}`} onClick={() => setActive(label)}><Icon type={iconFor(label)} />{label}</button> }
function Overview({ setActive }) { return <><section className="stats-row">{stats.map(([value, label, detail, icon]) => <article className="stat" key={label}><span className="stat-box"><Icon type={icon} /></span><div><strong>{value}</strong><h2>{label}</h2><p>{detail}</p></div></article>)}</section><section className="content-section"><div className="section-title"><h2>What would you like to update?</h2><p>Choose a section to edit its public website content</p></div><div className="actions-row">{actions.map(([title, detail, icon]) => <button className="action-card" key={title} onClick={() => setActive(title)}><span className="action-box"><Icon type={icon} /></span><span><strong>{title}</strong><small>{detail}</small></span><Icon type="arrow" /></button>)}</div></section><section className="bottom-grid"><article className="panel"><div className="panel-title"><div><h2>Recent Updates</h2><p>Latest changes across your website</p></div><button className="outline">View all</button></div><div className="updates">{updates.map(([title, detail, time]) => <div className="update" key={title}><span className="update-box"><Icon type="story" /></span><span><strong>{title}</strong><small>{detail}</small></span><time>{time}</time></div>)}</div></article><article className="panel"><div className="panel-title"><div><h2>Website Preview</h2><p>A glimpse of your public site</p></div><a className="outline" href="/" target="_blank" rel="noreferrer">Visit Website ↗</a></div><div className="site-preview"><nav><strong>GIFTSHORE</strong><span>Home　 Our Story　 Catalog　 Contact</span></nav><div className="preview-copy"><small>MADE TO DELIGHT</small><h3>Thoughtful Gifts<br />For Every Occasion</h3><b>EXPLORE CATALOG　→</b><i /></div></div></article></section></> }
export default function DashboardModern() { const [active, setActive] = useState('Dashboard'); const [content, setContent] = useState(() => getContent()); return <div className="modern-dashboard"><aside className="modern-sidebar"><div className="modern-brand"><span>✦</span><strong>GIFTSHORE</strong><small>MADE TO DELIGHT</small></div><NavLink label="Dashboard" active={active} setActive={setActive} />{groups.map(([heading, items]) => <div className="nav-group" key={heading}><p>{heading}</p>{items.map((item) => <NavLink key={item} label={item} active={active} setActive={setActive} />)}</div>)}<button className="logout" onClick={() => window.location.assign('/admin')}><Icon type="logout" />Logout</button></aside><main className="modern-main"><header className="modern-header"><div><p className="date-line">{new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p><h1>{active === 'Dashboard' ? 'Welcome back, Admin' : `Editing ${active}`} <span>{active === 'Dashboard' ? '👋' : '✦'}</span></h1><p>{active === 'Dashboard' ? "Here's what's happening with your website today." : 'Keep your public website content fresh and up to date.'}</p></div><div className="header-user"><button className="notify" aria-label="Notifications">♧<i /></button><span className="header-rule" /><span className="avatar">A</span><strong>Admin</strong><span className="down">⌄</span></div></header>{active === 'Dashboard' ? <Overview setActive={setActive} /> : <Editor section={active} initial={content} onSaved={setContent} onBack={() => setActive('Dashboard')} />}</main></div> }
